# Generated by Django 5.1.6 on 2025-03-04 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0002_alter_artist_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('album_name', models.CharField(blank=True, max_length=255)),
                ('genre', models.IntegerField(blank=True, choices=[(0, 'unspecified'), (1, 'mb'), (3, 'country'), (4, 'classic'), (5, 'rock'), (6, 'jazz')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.artist')),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
