# Generated by Django 5.1.6 on 2025-03-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.IntegerField(blank=True, choices=[(0, 'unspecified'), (1, 'mb'), (2, 'country'), (3, 'classic'), (4, 'rock'), (5, 'jazz')], null=True),
        ),
    ]
