# Generated by Django 5.1.6 on 2025-03-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('gender', models.SmallIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('first_release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_albums_released', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'db_table': 'artist',
            },
        ),
    ]
