# Generated by Django 5.1.6 on 2025-03-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'unspecified'), (1, 'male'), (2, 'female'), (3, 'other')], null=True),
        ),
    ]
